### ISSUE TITLE
styles.styl can't find base.styl

### ISSUE THREAD

**Issue by srl295** [nodejs/nodejs.org#23]
```
$ iojs build.js 
[metalsmith] build/static finished: 157ms
/Users/srl/git/new.nodejs.org/build.js:68
      if (err) { throw err; }
                 ^

Error: styles.styl:1:9
   1| @import 'base'
--------------^
   2| 

failed to locate @import file base.sty


    at Evaluator.visitImport (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/node_modules/stylus/lib/visitor/evaluator.js:901:21)
    at Evaluator.Visitor.visit (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitRoot (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/node_modules/stylus/lib/visitor/evaluator.js:693:27)
    at Evaluator.Visitor.visit (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.evaluate (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/node_modules/stylus/lib/visitor/evaluator.js:233:15)
    at Renderer.render (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/node_modules/stylus/lib/renderer.js:86:26)
    at /Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/lib/index.js:42:11
    at Array.forEach (native)
    at Ware.<anonymous> (/Users/srl/git/new.nodejs.org/node_modules/metalsmith-stylus/lib/index.js:22:12)
    at Ware.<anonymous> (/Users/srl/git/new.nodejs.org/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
    at next (/Users/srl/git/new.nodejs.org/node_modules/metalsmith/node_modules/ware/lib/index.js:85:20)
    at /Users/srl/git/new.nodejs.org/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/Users/srl/git/new.nodejs.org/plugins/filter-stylus-partials.js:16:9)
    at Ware.<anonymous> (/Users/srl/git/new.nodejs.org/node_modules/metalsmith/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
```

**Comment by snostorm** [comment]
I'm also having several issues in the repo as is (playing on it now myself). Somebody's local project state might have "carried over" to some later upgrades making fresh versions not run.

**Comment by fhemberger** [comment]
Sorry, hadn't merged @mikeal's PR for `metalsmith-stylus` into my fork yet (yay, time zones). Should work with a fresh `npm install`.

**Comment by snostorm** [comment]
@fhemberger I had to read that a few time before it clicked what was going on (I was looking for something changed in this repo, ha). Anyway, up and running now after dumping my `node_modules` and starting fresh. Thanks.

**Comment by fhemberger** [comment]
Sorry for the confusion ;)
