### ISSUE TITLE
watch is broken

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2443]
Could be I'm on Windows, but whenever I edit a markdown file, the server crashes for me:

```
C:\Users\xmr\Desktop\nodejs.org>node -v
v12.9.0

C:\Users\xmr\Desktop\nodejs.org>npm start

> nodejs.org@ start C:\Users\xmr\Desktop\nodejs.org
> npm run serve


> nodejs.org@ serve C:\Users\xmr\Desktop\nodejs.org
> node server.js

[metalsmith] build/static started
[metalsmith] build/layouts started
Server running at http://localhost:8080/en/
(node:1704) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:1704) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:1704) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:1704) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[metalsmith] build/static finished: 93.953ms
[metalsmith] build/layouts finished: 505.888ms
[metalsmith] build/ar started
[metalsmith] build/ca started
[metalsmith] build/de started
[metalsmith] build/en started
[metalsmith] build/es started
[metalsmith] build/fa started
[metalsmith] build/fr started
[metalsmith] build/gl started
[metalsmith] build/it started
[metalsmith] build/ja started
[metalsmith] build/ko started
[metalsmith] build/pt-br started
[metalsmith] build/ru started
[metalsmith] build/uk started
[metalsmith] build/zh-cn started
[metalsmith] build/zh-tw started
[metalsmith] build/gl finished: 6020.478ms
[metalsmith] build/de finished: 6286.983ms
[metalsmith] build/ca finished: 7431.933ms
[metalsmith] build/es finished: 7393.092ms
[metalsmith] build/zh-tw finished: 7292.250ms
[metalsmith] build/fr finished: 7363.862ms
[metalsmith] build/ar finished: 9901.110ms
[metalsmith] build/ko finished: 10096.795ms
[metalsmith] build/it finished: 10130.890ms
[metalsmith] build/ja finished: 10118.911ms
[metalsmith] build/zh-cn finished: 10085.629ms
[metalsmith] build/fa finished: 10195.471ms
[metalsmith] build/uk finished: 10112.800ms
[metalsmith] build/en finished: 10220.513ms
[metalsmith] build/pt-br finished: 10144.326ms
[metalsmith] build/ru finished: 10141.145ms
[metalsmith] build/en\about\working-groups.m started
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module './locale/en\about\working-groups.m/site.json'
Require stack:
- C:\Users\xmr\Desktop\nodejs.org\build.js
- C:\Users\xmr\Desktop\nodejs.org\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at i18nJSON (C:\Users\xmr\Desktop\nodejs.org\build.js:51:24)
    at Object.buildLocale (C:\Users\xmr\Desktop\nodejs.org\build.js:76:13)
    at FSWatcher.<anonymous> (C:\Users\xmr\Desktop\nodejs.org\server.js:53:13)
    at FSWatcher.emit (events.js:209:13)
    at FSWatcher.<anonymous> (C:\Users\xmr\Desktop\nodejs.org\node_modules\chokidar\index.js:199:15)
    at FSWatcher._emit (C:\Users\xmr\Desktop\nodejs.org\node_modules\chokidar\index.js:241:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\xmr\\Desktop\\nodejs.org\\build.js',
    'C:\\Users\\xmr\\Desktop\\nodejs.org\\server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs.org@ serve: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs.org@ serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2019-08-21T15_23_52_388Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs.org@ start: `npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs.org@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2019-08-21T15_23_52_419Z-debug.log

```

If I edit a layout or CSS file, the server reloads fine.

I tried updating chokidar (I'll make PRs for the deps tomorrow) and with the new version it doesn't crash, but throws a promised unhandled exception error.

**Comment by XhmikosR** [comment]
After the recent patches we are now down to this:

```
C:\Users\xmr\Desktop\nodejs.org>npm start

> nodejs.org@ start C:\Users\xmr\Desktop\nodejs.org
> npm run serve


> nodejs.org@ serve C:\Users\xmr\Desktop\nodejs.org
> node server.js

[metalsmith] build/static started
[metalsmith] build/layouts started
Server running at http://localhost:8080/en/
(node:2268) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:2268) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:2268) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:2268) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[metalsmith] build/static finished: 128.513ms
[metalsmith] build/layouts finished: 705.133ms
[metalsmith] build/ar started
[metalsmith] build/ca started
[metalsmith] build/de started
[metalsmith] build/en started
[metalsmith] build/es started
[metalsmith] build/fa started
[metalsmith] build/fr started
[metalsmith] build/gl started
[metalsmith] build/it started
[metalsmith] build/ja started
[metalsmith] build/ko started
[metalsmith] build/pt-br started
[metalsmith] build/ru started
[metalsmith] build/uk started
[metalsmith] build/zh-cn started
[metalsmith] build/zh-tw started
[metalsmith] build/gl finished: 7389.806ms
[metalsmith] build/ca finished: 7685.171ms
[metalsmith] build/fr finished: 7647.903ms
[metalsmith] build/es finished: 7667.870ms
[metalsmith] build/de finished: 7699.624ms
[metalsmith] build/zh-tw finished: 7640.854ms
[metalsmith] build/ar finished: 11352.201ms
[metalsmith] build/it finished: 11429.071ms
[metalsmith] build/ko finished: 11420.960ms
[metalsmith] build/ja finished: 11426.502ms
[metalsmith] build/zh-cn finished: 11402.738ms
[metalsmith] build/pt-br finished: 11417.009ms
[metalsmith] build/en finished: 11466.965ms
[metalsmith] build/ru finished: 11413.461ms
[metalsmith] build/fa finished: 11449.895ms
[metalsmith] build/uk finished: 11409.239ms
[metalsmith] build/en started
(node:2268) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'localesData' of undefined
    at Object.buildLocale (C:\Users\xmr\Desktop\nodejs.org\build.js:78:21)
    at FSWatcher.<anonymous> (C:\Users\xmr\Desktop\nodejs.org\server.js:53:13)
    at FSWatcher.emit (events.js:203:13)
    at FSWatcher.emitWithAll (C:\Users\xmr\Desktop\nodejs.org\node_modules\chokidar\index.js:487:8)
    at FSWatcher._emit (C:\Users\xmr\Desktop\nodejs.org\node_modules\chokidar\index.js:577:10)
    at C:\Users\xmr\Desktop\nodejs.org\node_modules\chokidar\lib\nodefs-handler.js:335:18
    at C:\Users\xmr\Desktop\nodejs.org\node_modules\chokidar\lib\nodefs-handler.js:218:48
    at Set.forEach (<anonymous>)
    at StatWatcher.<anonymous> (C:\Users\xmr\Desktop\nodejs.org\node_modules\chokidar\lib\nodefs-handler.js:218:26)
    at StatWatcher.emit (events.js:203:13)
(node:2268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Should I try passing `localesData` in serve.js `buildLocale`?

**Comment by XhmikosR** [comment]
@MaledongGit: here's more info

In server.js

https://github.com/nodejs/nodejs.org/blob/411eac482064734e6dfe2bab7d29c471f930a5c9/server.js#L59

But in build.js buildLocale is using `opts.localesData` which is undefined and throws on watch

https://github.com/nodejs/nodejs.org/blob/411eac482064734e6dfe2bab7d29c471f930a5c9/build.js#L78

**Comment by ghost** [comment]
@XhmikosR , fixed it, you can have a review at https://github.com/nodejs/nodejs.org/pull/2457, thanks!!!
