### ISSUE TITLE
Node V5 has issues with installing behind proxies

### ISSUE THREAD

**Issue by wyattbiker** [nodejs/nodejs.org#395]
am behind corporate proxy. I ve tried everything under the sun with flags and configs. (yes i set up the --proxy and --https-proxy).  I reverted back to 0.12 and everything works fine. 

Any ideas?

Here is the message:

```
Enter node package to install: ws
Enter -g for global install:

> bufferutil@1.1.0 install /mnt/mydir/mytest/node_modules/bufferutil
> node-gyp rebuild


gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1057:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:596:8)
gyp ERR! System Linux 2.6.32-573.1.1.el6.x86_64
gyp ERR! command "/mnt/node/bin/node" "/mnt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/mydir/mytest/node_modules/bufferutil
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.1.0 bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.1.0 Exit status 1
```

**Comment by phillipj** [comment]
This is most likely a npm issue, rather than the Node.js runtime. 

A similar npm issue report: https://github.com/npm/npm/issues/8872. If the proposed solution doesn't work for you, I'd suggest you join the ongoing discussion in that specific issue.
