### ISSUE TITLE
Unable to start the site through "npm start"

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#788]
- **localhost**:
- **Chrome Latest Version**:
- **Windows 7 64-bit**:

I just downloaded the code and am trying to run the project.  As given in the instructions I typed 
`--npm install` (this worked fine)
`--npm start`:  When I run this I get the following error 

```
> npm run serve


> nodejs.org@1.0.0 serve C:\Written Programs\OpenSourceProjects\nodejs.org
> node server.js

http://localhost:8080/en/
C:\Written Programs\OpenSourceProjects\nodejs.org\scripts\event-geo.js:111
  load().regions.forEach((reg) => {
        ^

TypeError: Cannot read property 'regions' of undefined
    at module.exports.load.regions.forEach.reg.meetups.forEach.reg.conferences.f
orEach (C:\Written Programs\OpenSourceProjects\nodejs.org\scripts\event-geo.js:1
11:9)
    at C:\Written Programs\OpenSourceProjects\nodejs.org\build.js:236:100
    at cb (C:\Written Programs\OpenSourceProjects\nodejs.org\node_modules\ncp\li
b\ncp.js:255:37)
    at C:\Written Programs\OpenSourceProjects\nodejs.org\node_modules\ncp\lib\nc
p.js:108:16
    at C:\Written Programs\OpenSourceProjects\nodejs.org\node_modules\ncp\lib\nc
p.js:227:14
    at FSReqWrap.oncomplete (fs.js:82:15)_  
```

**Comment by saadq** [comment]
What version of Node are you using? The [README](https://github.com/nodejs/nodejs.org#contributing) states:

> Note: You'll need Node.js v4 or newer as the build system uses some native ES2015 features.

You can check your version by doing `node --version` inside the command line.
